# Change these first
owner: Aclsu 
repo: pof-status
user-agent: Aclsu
assignees: 
  - Aclsu
sites:
  - name: Phillips Ormonde Fitzpatrick - IPSys
    url: https://ipsys.pof.com.au
    icon: https://ipsys.pof.com.au/dist/images/favicon.ico
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
  - name: Phillips Ormonde Fitzpatrick - Website
    url: https://www.pof.com.au
    icon: https://cdn.pof.com.au/app/themes/POF/dist/images/favicon.ico
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
  - name: IP Organisers - Website
    url: https://www.iporganisers.com.au
    icon: https://cdn.iporganisers.com.au/app/themes/iporganisers/assets/img/favicon.ico
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
status-website:
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  cname: status.pof.com.au
  theme: night
  favicon: https://cdn.pof.com.au/app/themes/POF/dist/images/favicon.ico
  logoUrl: https://www.pof.com.au/app/themes/POF/dist/images/POF-Logo-Reverse.svg
  name: Application Status
  introTitle: 
  introMessage: This status page uses **real-time** data to display the current and historical status of Phillips Ormonde Fitzpatrick applications.
  navbar:
    - title: Status
      href: /
    - title: IPSys
      href: https://ipsys.pof.com.au/
    - title: POF
      href: https://www.pof.com.au/
    - title: IPO
      href: https://www.iporganisers.com.au/
i18n:
  footer: For all issues or queries please [contact us here](mailto://info@pof.com.au?subject=POF+Status+Query).

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
